const mongoose = require('mongoose');

/**
 * ActionItem — surfaced alerts + duties for the user's Today tab.
 *
 * MASTER_PLAN §6 — suggestion card standard.
 *
 * Sources:
 *   - sentinel        — auto-generated by Sentinel service (missed tasks, data issues, risk)
 *   - chief-analyst   — CA's prioritized actions (Phase 4+)
 *   - trading-bot     — bot-generated suggestions awaiting approval
 *   - pattern-miner   — recurring-mistake warnings (Phase 3+)
 *   - user-duty       — scheduled personal duties (journal review, etc.)
 *
 * Lifecycle:
 *   new → acknowledged → dismissed | resolved
 */
const actionItemSchema = new mongoose.Schema({
  title: { type: String, required: true },
  description: { type: String, default: '' },
  impact: { type: String, default: '' },          // "if you skip, this happens..."
  action: { type: String, default: '' },          // "click here to..." OR UI route hint

  priority: {
    type: String,
    enum: ['URGENT', 'HIGH', 'MEDIUM', 'LOW'],
    required: true,
    index: true,
  },
  source: {
    type: String,
    enum: ['sentinel', 'chief-analyst', 'trading-bot', 'pattern-miner', 'user-duty'],
    required: true,
    index: true,
  },

  // Optional structured fields
  symbol: { type: String, default: '' },
  botId: { type: String, default: '' },
  relatedSetupId: { type: mongoose.Schema.Types.ObjectId, ref: 'TradeSetup', default: null },
  deadline: { type: Date, default: null },

  // State
  status: {
    type: String,
    enum: ['new', 'acknowledged', 'dismissed', 'resolved', 'expired'],
    default: 'new',
    index: true,
  },
  dedupKey: { type: String, default: '', index: true }, // prevents duplicate alerts
  resolvedAt: { type: Date, default: null },
}, { timestamps: true });

actionItemSchema.index({ status: 1, priority: 1, createdAt: -1 });

module.exports = mongoose.model('ActionItem', actionItemSchema);
