# This is a basic workflow that is manually triggered for repository refresh
name: Repository Refresh Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      refresh_type:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Type of refresh to perform'
        # Default value if no value is explicitly provided
        default: 'full'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: choice
        options:
          - full
          - cache-clear
          - index-rebuild

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "refresh"
  refresh:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for complete indexing
        
    # Display repository information
    - name: Display repository info
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Refresh type: ${{ inputs.refresh_type }}"
        echo "Triggered by: ${{ github.actor }}"
        echo "Branch: ${{ github.ref }}"
        echo "Commit: ${{ github.sha }}"
        
    # Perform repository refresh actions
    - name: Repository refresh actions
      run: |
        echo "Performing repository refresh..."
        echo "Listing repository contents:"
        ls -la
        echo "Git status:"
        git status
        echo "Recent commits:"
        git log --oneline -n 5
        echo "Repository refresh completed successfully!"
